/**
 * LARDER RECIPE FORMAT STANDARD
 * All recipes must follow this structure exactly.
 *
 * id:          slugified-title + "-" + timestamp e.g. "chicken-tacos-1714000000000"
 * title:       Title Case
 * description: 1-2 sentences. Include cost + portions e.g. "About €10 for 4 portions."
 * tags:        Array from approved list: Baking, Dessert, Portuguese, Dinner, Quick,
 *              Vegetarian, Fish, Chicken, Pasta, Italian, Breakfast, Soup
 * servings:    Number
 * prepTime:    "X min" format always
 * cookTime:    "X min" format always
 * ingredients: [{ name: "Ingredient, descriptor", amount: "metric amount" }]
 *              - name in Title Case, descriptor after comma e.g. "Chicken breast, diced"
 *              - amount always metric: g, ml, kg, tsp, tbsp, handful, "to taste", "to serve"
 * method:      Array of strings, each a complete sentence or logical step
 * notes:       1-2 practical tips. Optional but preferred.
 * createdAt:   Date.now()
 */

export const STORAGE_KEY = "larder-recipes-v1";
export const COLLECTIONS_KEY = "larder-collections-v1";
export const PANTRY_KEY = "larder-pantry-v1";
export const SHOPPING_LIST_KEY = "larder-shopping-list-v1";

export const API_MODEL = "claude-sonnet-4-20250514";

export const DUNNES_AISLES = [
  { name: "Fresh Produce", icon: "🥦", keywords: ["spinach","lettuce","onion","garlic","pepper","tomato","lemon","lime","cucumber","broccoli","mushroom","spring onion","coriander","parsley","ginger","potato","carrot","courgette","herb","tenderstem","fresh chilli","avocado","bean sprout"] },
  { name: "Dairy & Eggs", icon: "🧀", keywords: ["egg","milk","cream","butter","cheese","mozzarella","cheddar","parmesan","halloumi","burrata","yogurt","crème fraîche","sour cream","flora"] },
  { name: "Meat & Fish", icon: "🥩", keywords: ["chicken","beef","mince","chorizo","bacon","prawn","calamari","fish","salmon","sea bass","pork","lamb","steak","sausage"] },
  { name: "Fresh Pasta & Chilled", icon: "🍝", keywords: ["gnocchi","fresh pasta","fresh noodle","tortilla","flatbread","naan","brioche","puff pastry"] },
  { name: "Dry Goods & Pasta", icon: "🫙", keywords: ["pasta","spaghetti","penne","rigatoni","fusilli","orzo","rice","noodle","flour","sugar","oat","lentil","bean","chickpea","tin","tinned","passata","stock","breadcrumb","tortilla chip","doritos","bun"] },
  { name: "Condiments & Sauces", icon: "🧴", keywords: ["soy sauce","honey","tomato purée","tomato paste","ketchup","mustard","bbq sauce","harissa","pesto","chipotle","hot sauce","peri-peri","salsa","mayo","mayonnaise","worcestershire","balsamic","vinegar","oil","sesame oil","chilli oil","vodka","cream","single cream","double cream"] },
  { name: "Spices & Baking", icon: "🫙", keywords: ["paprika","cumin","cajun","oregano","cinnamon","vanilla","chilli","pepper","salt","seasoning","five spice","italian seasoning","garlic granule","onion granule","sugar","flour","baking"] },
];

export const TAG_COLORS = {
  default: { bg: "#f0ebe3", text: "#5c4a2a" },
  Baking: { bg: "#fde8d0", text: "#b84800" },
  Dessert: { bg: "#fce4ec", text: "#880e4f" },
  Portuguese: { bg: "#e8f4ea", text: "#2e7d32" },
  Dinner: { bg: "#e3f2fd", text: "#1565c0" },
  Quick: { bg: "#f3e5f5", text: "#6a1b9a" },
  Vegetarian: { bg: "#e8f5e9", text: "#1b5e20" },
  Fish: { bg: "#e0f7fa", text: "#00695c" },
  Chicken: { bg: "#fff3e0", text: "#e65100" },
  Pasta: { bg: "#fff8e1", text: "#f57f17" },
  Italian: { bg: "#fce8e8", text: "#b71c1c" },
  Breakfast: { bg: "#f9fbe7", text: "#558b2f" },
  Soup: { bg: "#e8eaf6", text: "#283593" },
};

export const SAMPLE_COLLECTIONS = [
  { id: "col-1", name: "Portuguese", emoji: "🇵🇹", recipeIds: ["1"], createdAt: Date.now() - 50000 },
  { id: "col-2", name: "Baking", emoji: "🧁", recipeIds: ["1"], createdAt: Date.now() - 40000 },
  { id: "col-3", name: "Chicken Week", emoji: "🐔", recipeIds: ["2", "3", "4"], createdAt: Date.now() - 30000 },
];

export const SAMPLE_RECIPES = [
  {
    id: "pastes-de-nata-1",
    title: "Pastéis de Nata",
    description: "Classic Portuguese custard tarts with flaky pastry and a caramelised custard filling. Makes 12 tarts.",
    tags: ["Baking", "Dessert", "Portuguese"],
    servings: 12,
    prepTime: "45 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Puff pastry", amount: "500g" },
      { name: "Egg yolks", amount: "6" },
      { name: "Caster sugar", amount: "200g" },
      { name: "Plain flour", amount: "30g" },
      { name: "Whole milk", amount: "250ml" },
      { name: "Double cream", amount: "100ml" },
      { name: "Cinnamon stick", amount: "1" },
      { name: "Lemon, zested", amount: "1" },
      { name: "Vanilla extract", amount: "1 tsp" },
    ],
    method: [
      "Preheat oven to 250°C. Grease a 12-hole muffin tin.",
      "Roll pastry tightly into a log, then slice into 12 equal rounds.",
      "Press each round into the muffin tin, working up the sides with your thumb.",
      "Whisk egg yolks, sugar and flour in a saucepan. Slowly add milk and cream.",
      "Add cinnamon stick and lemon zest. Cook over medium heat, stirring constantly, until thickened.",
      "Remove from heat, stir in vanilla and strain through a sieve.",
      "Pour custard into pastry cases and bake for 15–20 minutes until tops are dark and blistered.",
      "Cool for 10 minutes before removing. Dust with cinnamon and icing sugar to serve.",
    ],
    notes: "The high oven temperature is key — don't be afraid of the dark blisters on top.",
    createdAt: Date.now() - 86400000,
  },
  {
    id: "air-fryer-nachos-1",
    title: "Air Fryer Nachos",
    description: "Loaded nachos built in layers straight in the air fryer. Quick, messy, and very good. About €13 for 2 portions.",
    tags: ["Dinner", "Quick"],
    servings: 2,
    prepTime: "10 min",
    cookTime: "10 min",
    ingredients: [
      { name: "Doritos", amount: "2 bags" },
      { name: "Beef mince", amount: "450g" },
      { name: "Black beans", amount: "1 tin" },
      { name: "Cheese, grated", amount: "200g" },
      { name: "Pickled jalapeños", amount: "50g" },
      { name: "Fresh jalapeños, sliced", amount: "2" },
      { name: "Onion, diced", amount: "1" },
      { name: "Sour cream", amount: "100ml" },
      { name: "Salsa verde", amount: "100ml" },
      { name: "Pico de gallo", amount: "100ml" },
      { name: "Guacamole", amount: "100ml" },
    ],
    method: [
      "Brown the beef mince in a pan and season. Drain any excess fat.",
      "Layer into the air fryer basket: Doritos first, then beef, black beans, jalapeños, onion and cheese. Repeat if depth allows.",
      "Air fry at 180°C for 6–8 minutes until cheese is melted and edges are crispy.",
      "Top with salsa verde, sour cream, pico de gallo and guacamole. Serve immediately.",
    ],
    notes: "Add toppings cold after cooking — they'll go soggy inside the air fryer.",
    createdAt: Date.now() - 82000000,
  },
  {
    id: "special-fried-rice-1",
    title: "Special Fried Rice",
    description: "Chorizo, prawns and calamari fried rice with scrambled egg, seasoned with soy and Worcestershire. About €15 for 4 portions.",
    tags: ["Dinner", "Fish"],
    servings: 4,
    prepTime: "15 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Jasmine or basmati rice, cooked and cooled", amount: "750g" },
      { name: "Chorizo, diced", amount: "200g" },
      { name: "Prawns, peeled and deveined", amount: "250g" },
      { name: "Calamari, sliced into rings", amount: "200g" },
      { name: "Eggs, beaten", amount: "3" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Onion, finely chopped", amount: "1" },
      { name: "Red bell pepper, diced", amount: "1" },
      { name: "Spring onions, chopped", amount: "3" },
      { name: "Soy sauce", amount: "3 tbsp" },
      { name: "Worcestershire sauce", amount: "1½ tsp" },
      { name: "Sugar", amount: "1 tsp" },
      { name: "Smoked paprika", amount: "½ tsp" },
      { name: "Vegetable or sesame oil", amount: "2 tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
      { name: "Lime wedges", amount: "to serve" },
    ],
    method: [
      "Heat oil in a large pan or wok. Add chorizo and cook 3–4 minutes until crispy.",
      "Push chorizo aside, add prawns and calamari. Cook 2–3 minutes until prawns are pink. Remove and set aside.",
      "Pour in beaten eggs and scramble until just set. Mix through the chorizo.",
      "Add garlic, onion and pepper. Sauté until fragrant, then add smoked paprika.",
      "Add rice and toss well, breaking up any clumps.",
      "Stir in soy sauce, Worcestershire sauce and sugar. Return prawns and calamari and mix well.",
      "Toss in spring onions. Serve hot with lime wedges.",
    ],
    notes: "Day-old rice fries much better — it's drier so it won't steam and go clumpy.",
    createdAt: Date.now() - 81000000,
  },
  {
    id: "bbq-chicken-potato-skillet-1",
    title: "BBQ Chicken Potato Skillet",
    description: "Crispy air-fryer potatoes tossed with BBQ-glazed chicken, peppers and melted mozzarella. About €12 for 4 portions.",
    tags: ["Chicken", "Dinner"],
    servings: 4,
    prepTime: "15 min",
    cookTime: "30 min",
    ingredients: [
      { name: "Potatoes, cubed", amount: "800g" },
      { name: "Chicken breast, diced", amount: "500g" },
      { name: "Peppers, sliced", amount: "2" },
      { name: "Onion, finely diced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "2" },
      { name: "Smoked paprika", amount: "1½ tbsp" },
      { name: "Garlic granules", amount: "1½ tbsp" },
      { name: "Dried oregano", amount: "1½ tsp" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "BBQ sauce", amount: "2 tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Mozzarella, grated", amount: "80g" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Season potatoes with half the paprika, garlic granules, oregano, salt and pepper. Air fry at 190°C for 20 minutes until crispy.",
      "Season chicken with remaining spices and fry in a pan until browned.",
      "Add onions and peppers, cook until soft. Add garlic, tomato purée, BBQ sauce and honey. Stir well.",
      "Add crispy potatoes to the pan and mix everything together.",
      "Scatter mozzarella on top and grill until bubbling. Serve immediately.",
    ],
    notes: "Get the potatoes properly crispy before adding — they'll soften slightly under the sauce so they need a head start.",
    createdAt: Date.now() - 80000000,
  },
  {
    id: "chicken-halloumi-flatbreads-1",
    title: "Chicken & Halloumi Flatbreads",
    description: "Grilled chicken and halloumi in warm flatbreads with tzatziki. Simple, fresh and endlessly adaptable. About €12 for 2 portions.",
    tags: ["Chicken", "Dinner", "Quick"],
    servings: 2,
    prepTime: "10 min",
    cookTime: "15 min",
    ingredients: [
      { name: "Chicken breast or thighs", amount: "300g" },
      { name: "Halloumi, sliced", amount: "150g" },
      { name: "Flatbreads", amount: "2" },
      { name: "Tzatziki", amount: "4 tbsp" },
      { name: "Olive oil", amount: "1 tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Season chicken and cook in a hot pan until cooked through. Slice or shred.",
      "Fry halloumi slices in the same pan until golden on both sides, about 2 minutes per side.",
      "Warm flatbreads in a dry pan for 30 seconds each side.",
      "Spread tzatziki on each flatbread, top with chicken and halloumi. Add any extras and wrap.",
    ],
    notes: "Add whatever you have — roasted peppers, chilli sauce, fresh tomato, rocket. Make it up.",
    createdAt: Date.now() - 79000000,
  },
  {
    id: "chicken-chorizo-one-pan-rice-1",
    title: "Chicken & Chorizo One Pan Rice",
    description: "Everything goes in one pan — chicken, chorizo, rice and stock — and comes out smoky and satisfying. About €10 for 4 portions.",
    tags: ["Chicken", "Dinner"],
    servings: 4,
    prepTime: "10 min",
    cookTime: "25 min",
    ingredients: [
      { name: "Chicken breast, diced", amount: "400g" },
      { name: "Chorizo, diced", amount: "140g" },
      { name: "Onion, diced", amount: "1" },
      { name: "Garlic cloves, crushed", amount: "3" },
      { name: "Long-grain rice", amount: "260g" },
      { name: "Chicken stock", amount: "700ml" },
      { name: "Tomato purée", amount: "2 tbsp" },
      { name: "Smoked paprika", amount: "1 tbsp" },
      { name: "Garlic granules", amount: "1 tbsp" },
      { name: "Onion granules", amount: "1 tbsp" },
      { name: "Cheese, grated", amount: "80g" },
      { name: "Fresh parsley", amount: "handful" },
    ],
    method: [
      "Fry onion and chorizo for a few minutes. Add garlic and fry for 30 seconds.",
      "Add chicken with garlic granules and paprika. Cook until coloured all over.",
      "Add tomato purée, then uncooked rice. Stir for a minute.",
      "Pour in stock and bring to a boil. Reduce to low, cover and cook 15–20 minutes, stirring occasionally.",
      "Once rice is done, stir through parsley and scatter cheese on top.",
    ],
    notes: "Be generous with the tomato purée — it needs more than you think. Serve with broccoli on the side.",
    createdAt: Date.now() - 78000000,
  },
  {
    id: "halloumi-chorizo-spaghetti-1",
    title: "Halloumi & Chorizo Spaghetti",
    description: "Crispy chorizo and golden halloumi in a creamy tomato sauce with a drizzle of honey. About €8 for 4 portions.",
    tags: ["Pasta", "Dinner", "Quick"],
    servings: 4,
    prepTime: "5 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Spaghetti", amount: "400g" },
      { name: "Chorizo, diced", amount: "200g" },
      { name: "Halloumi, diced", amount: "140g" },
      { name: "Garlic cloves, minced", amount: "4" },
      { name: "Tomato purée", amount: "2 tbsp" },
      { name: "Single cream", amount: "120ml" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Italian seasoning", amount: "1 tbsp" },
      { name: "Chilli flakes", amount: "to taste" },
      { name: "Fresh parsley", amount: "handful" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Cook spaghetti in well-salted boiling water. Reserve a cup of pasta water before draining.",
      "Fry chorizo and halloumi until starting to crisp. Add honey and stir.",
      "Add garlic and tomato purée, cook for a minute.",
      "Add cream, Italian seasoning and a splash of pasta water. Simmer a few minutes.",
      "Toss in cooked pasta and loosen with more pasta water as needed.",
      "Serve topped with parsley and chilli flakes.",
    ],
    notes: "Don't hold back on the chorizo. The honey at the crispy stage is the key move.",
    createdAt: Date.now() - 77000000,
  },
  {
    id: "cheeseburger-flatbread-pizza-1",
    title: "Cheeseburger Flatbread Pizza",
    description: "Saucy beef mince on flatbreads, grilled with cheese and loaded with pickles and burger sauce. About €10 for 2 portions.",
    tags: ["Dinner", "Quick"],
    servings: 2,
    prepTime: "10 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Lean beef mince", amount: "500g" },
      { name: "Onion, finely diced", amount: "1" },
      { name: "Garlic cloves, grated", amount: "2" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Tomato ketchup", amount: "2 tbsp" },
      { name: "Mustard", amount: "2 tbsp" },
      { name: "Beef stock", amount: "200ml" },
      { name: "Cheese, grated", amount: "80g" },
      { name: "Flatbreads", amount: "2" },
      { name: "Pickles, burger sauce, diced onion", amount: "to garnish" },
    ],
    method: [
      "Fry beef mince until browned. Add onion and cook until soft.",
      "Add garlic and cook 1 minute. Add tomato purée, ketchup and mustard. Cook 2–3 minutes.",
      "Pour in stock and cook until thickened.",
      "Spoon beef onto flatbreads, top with cheese.",
      "Grill or air fry until golden and bubbling. Add garnishes and serve.",
    ],
    notes: "Works great in the air fryer. Could add mushrooms or bacon to the mince to mix it up.",
    createdAt: Date.now() - 76000000,
  },
  {
    id: "hot-honey-cajun-beef-pasta-1",
    title: "Hot Honey Cajun Beef Pasta",
    description: "Spiced beef mince in a rich tomato sauce with Cajun seasoning and a hit of honey. About €9 for 2 portions.",
    tags: ["Pasta", "Dinner", "Quick"],
    servings: 2,
    prepTime: "5 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Pasta", amount: "200g" },
      { name: "Beef mince (5% fat)", amount: "250g" },
      { name: "Onion, diced", amount: "1 small" },
      { name: "Garlic cloves, crushed", amount: "2" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Tinned tomatoes", amount: "400g" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Smoked paprika", amount: "1 tsp" },
      { name: "Cajun seasoning", amount: "1 tbsp" },
      { name: "Onion granules", amount: "1 tsp" },
      { name: "Cheddar, grated", amount: "to top" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Fry onion until soft, then add beef mince and cook through.",
      "Boil pasta in a separate pot.",
      "Add tomato purée, garlic, tinned tomatoes, honey, paprika, Cajun seasoning and a ladle of pasta water to the mince.",
      "Simmer until thickened. Stir in drained pasta. Top with cheddar.",
    ],
    notes: "The honey balances the Cajun heat — don't skip it.",
    createdAt: Date.now() - 75000000,
  },
  {
    id: "honey-bbq-beef-sliders-1",
    title: "Honey BBQ Cheesy Beef Sliders",
    description: "Saucy beef sliders in brioche buns, baked together with cheese and a garlic butter glaze. About €12 for 4 portions.",
    tags: ["Dinner"],
    servings: 4,
    prepTime: "15 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Brioche buns", amount: "4" },
      { name: "Beef mince (5% fat)", amount: "400g" },
      { name: "Onion, diced", amount: "1" },
      { name: "Oil", amount: "½ tbsp" },
      { name: "Balsamic vinegar", amount: "1 tbsp" },
      { name: "BBQ seasoning", amount: "1 tbsp" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Worcestershire sauce", amount: "½ tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Passata", amount: "80g" },
      { name: "BBQ sauce", amount: "1 tbsp" },
      { name: "Cheese mix, grated", amount: "90g" },
      { name: "Butter, softened", amount: "10g" },
      { name: "Garlic clove, crushed", amount: "1" },
      { name: "Parsley, chopped", amount: "to top" },
      { name: "Sesame seeds", amount: "to top" },
    ],
    method: [
      "Fry onion in oil and balsamic vinegar until soft. Add beef and cook through.",
      "Add BBQ seasoning, Worcestershire sauce, honey, tomato purée and passata. Simmer a couple of minutes.",
      "Place bun bottoms in a baking dish. Drizzle BBQ sauce on each, top with beef mix then cheese.",
      "Add bun tops. Mix butter with garlic and parsley, brush over the tops. Sprinkle sesame seeds.",
      "Cover with foil and bake at 180°C for 5 minutes. Remove foil and bake another 5 minutes.",
    ],
    notes: "Bake them together so the buns steam slightly under the foil — pull-apart style.",
    createdAt: Date.now() - 74000000,
  },
  {
    id: "chicken-noodle-stir-fry-1",
    title: "Chicken Noodle Stir Fry",
    description: "Minced chicken with noodles, spinach and spring onion in a sesame soy sauce. About €10 for 2 portions.",
    tags: ["Chicken", "Dinner", "Quick"],
    servings: 2,
    prepTime: "10 min",
    cookTime: "15 min",
    ingredients: [
      { name: "Noodles", amount: "350g" },
      { name: "Chicken mince", amount: "300g" },
      { name: "Spinach", amount: "250g" },
      { name: "Mushrooms, sliced", amount: "100g" },
      { name: "Onion, sliced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Light soy sauce", amount: "3 tbsp" },
      { name: "Dark soy sauce", amount: "1 tbsp" },
      { name: "Sesame oil", amount: "1 tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Chilli oil", amount: "1 tsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Heat a pan until very hot. Add chicken mince and break down. Let it brown.",
      "Add mushrooms, onion, garlic, salt and pepper. Cook on high heat 3–4 minutes, stirring continuously.",
      "Cook noodles according to pack and drain.",
      "Add spinach, noodles, both soy sauces, sesame oil and honey. Stir-fry 3–4 minutes to get a slight char.",
      "Add chilli oil, taste and adjust seasoning. Serve immediately.",
    ],
    notes: "High heat is key for the char on the noodles.",
    createdAt: Date.now() - 73000000,
  },
  {
    id: "crispy-beef-tacos-1",
    title: "Crispy Beef Tacos",
    description: "Spiced beef in folded tortillas baked until crisp, with a chipotle yogurt dipping sauce. Makes 6 tacos.",
    tags: ["Dinner"],
    servings: 3,
    prepTime: "15 min",
    cookTime: "30 min",
    ingredients: [
      { name: "Beef mince (5% fat)", amount: "500g" },
      { name: "Onion, finely chopped", amount: "1" },
      { name: "Garlic cloves, chopped", amount: "3" },
      { name: "Chipotle paste", amount: "2 tbsp" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Beef stock", amount: "150ml" },
      { name: "Smoked paprika", amount: "1 tsp" },
      { name: "Ground cumin", amount: "1 tsp" },
      { name: "Ground coriander", amount: "1 tsp" },
      { name: "Dried oregano", amount: "1 tsp" },
      { name: "Chilli powder", amount: "½ tsp" },
      { name: "Wholemeal wraps", amount: "6" },
      { name: "Cheese, grated", amount: "150g" },
      { name: "Olive oil, for brushing", amount: "½ tbsp" },
      { name: "Greek yogurt (0% fat)", amount: "100g" },
      { name: "Soured cream", amount: "50g" },
      { name: "Lime, juiced", amount: "1" },
      { name: "Honey", amount: "1 tbsp" },
    ],
    method: [
      "Preheat oven to 200°C.",
      "Sauté onion 3–4 minutes. Add beef and garlic, cook until browned. Add all spices.",
      "Add chipotle paste, tomato purée and stock. Simmer 10 minutes until no excess liquid.",
      "Divide beef and cheese between wraps. Fold closed and press firmly. Brush with oil.",
      "Bake on a lined tray for 15 minutes until crisp.",
      "Mix yogurt, soured cream, remaining chipotle paste, lime juice and honey for the dipping sauce.",
      "Serve tacos with chipotle sauce on the side.",
    ],
    notes: "Press the folded wraps firmly before baking — they need contact with the tray to crisp up.",
    createdAt: Date.now() - 71000000,
  },
  {
    id: "chicken-veg-fusion-pasta-1",
    title: "Chicken & Veg Fusion Pasta",
    description: "Big-batch pasta with chicken, broccoli, mushrooms and peppers seasoned with soy, sesame and paprika. About €12 for 4 portions.",
    tags: ["Chicken", "Pasta", "Dinner"],
    servings: 4,
    prepTime: "15 min",
    cookTime: "25 min",
    ingredients: [
      { name: "Pasta (penne or fusilli)", amount: "450g" },
      { name: "Chicken breast, diced", amount: "500g" },
      { name: "Onions, chopped", amount: "2" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Broccoli, cut into florets", amount: "½ head" },
      { name: "Bell pepper, diced", amount: "1" },
      { name: "Mushrooms, sliced", amount: "150g" },
      { name: "Olive oil", amount: "3 tbsp" },
      { name: "Light soy sauce", amount: "2 tbsp" },
      { name: "Dark soy sauce", amount: "1 tbsp" },
      { name: "Sesame oil", amount: "2 tsp" },
      { name: "Smoked paprika", amount: "1 tsp" },
      { name: "Herbes de Provence", amount: "1 tsp" },
      { name: "Fresh ginger, grated", amount: "1 tsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Cook pasta in salted boiling water until al dente. Reserve ½ cup pasta water. Drain.",
      "Heat olive oil in a large pan. Season chicken with paprika, herbes de Provence, salt and pepper. Cook until golden and through.",
      "Add onions and garlic, fry 2–3 minutes until soft.",
      "Add broccoli, pepper and mushrooms. Stir-fry with both soy sauces and sesame oil until veg has a little bite.",
      "Add pasta and toss. Add pasta water to loosen if needed.",
    ],
    notes: "Use whatever veg needs using. The soy and sesame make it taste very different from a standard pasta.",
    createdAt: Date.now() - 70000000,
  },
  {
    id: "harissa-honey-halloumi-chicken-1",
    title: "Harissa Honey Halloumi Chicken",
    description: "Hasselback chicken stuffed with halloumi and brushed in a sticky harissa honey glaze, air fried until golden. About €16 for 2 portions.",
    tags: ["Chicken", "Dinner"],
    servings: 2,
    prepTime: "15 min",
    cookTime: "22 min",
    ingredients: [
      { name: "Chicken breasts, large", amount: "2" },
      { name: "Halloumi, sliced", amount: "100g" },
      { name: "Harissa paste", amount: "4 tsp" },
      { name: "Honey", amount: "4 tsp" },
      { name: "Tenderstem broccoli", amount: "150g" },
      { name: "Potatoes, cubed", amount: "400g" },
      { name: "Mixed herbs", amount: "1 tsp" },
      { name: "Olive oil", amount: "1 tbsp" },
    ],
    method: [
      "Hasselback the chicken breasts — slice deep cuts across the top without going all the way through.",
      "Push a half slice of halloumi into each slit.",
      "Mix harissa and honey. Brush all over the chicken and into the cuts.",
      "Air fry at 180°C for 18–22 minutes. Baste with more harissa honey halfway through.",
      "Serve with griddled tenderstem broccoli and herby air fryer potatoes.",
    ],
    notes: "Light halloumi works best — it melts into the chicken rather than going rubbery. Don't skip the halfway baste.",
    createdAt: Date.now() - 69000000,
  },
  {
    id: "spicy-tomato-burrata-pasta-1",
    title: "Spicy Tomato Burrata Pasta",
    description: "Cherry tomatoes and chilli oil in a vodka cream sauce, finished with a whole burrata melted on top. About €12 for 4 portions.",
    tags: ["Pasta", "Dinner", "Vegetarian"],
    servings: 4,
    prepTime: "10 min",
    cookTime: "25 min",
    ingredients: [
      { name: "Pasta", amount: "350g" },
      { name: "Butter", amount: "2 tbsp" },
      { name: "Chilli oil", amount: "1 tbsp" },
      { name: "Garlic cloves, minced", amount: "2" },
      { name: "Red pepper flakes", amount: "½ tsp" },
      { name: "Cherry tomatoes", amount: "300g" },
      { name: "Tomato purée", amount: "4 tbsp" },
      { name: "Vodka", amount: "60ml" },
      { name: "Single cream", amount: "240ml" },
      { name: "Burrata", amount: "1" },
      { name: "Parmesan, grated", amount: "to serve" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Cook pasta in heavily salted water. Reserve ¼ cup pasta water before draining.",
      "Melt butter with chilli oil over medium-low heat. Add garlic and pepper flakes — keep heat low.",
      "Add cherry tomatoes, salt, pepper and pasta water. Cover and cook 5–8 minutes until tomatoes are about to burst.",
      "Add tomato purée and stir until dark red. Add vodka and cook until absorbed.",
      "Add cream in two additions, letting it thicken between each.",
      "Toss in cooked pasta. Serve with burrata on top and parmesan and chilli flakes to finish.",
    ],
    notes: "Add the cream gradually — it needs to thicken between additions. The vodka adds depth without tasting of alcohol.",
    createdAt: Date.now() - 68000000,
  },
  {
    id: "cheesy-mexican-beef-pasta-1",
    title: "Cheesy Mexican Honey Beef Pasta",
    description: "Beef mince with fajita seasoning, cream and mozzarella — pasta meets a Mexican bowl. About €10 for 4 portions.",
    tags: ["Pasta", "Dinner"],
    servings: 4,
    prepTime: "10 min",
    cookTime: "25 min",
    ingredients: [
      { name: "Pasta", amount: "300g" },
      { name: "Beef mince", amount: "500g" },
      { name: "Onion, finely diced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Fajita seasoning", amount: "2 tbsp" },
      { name: "Garlic powder", amount: "1 tbsp" },
      { name: "Smoked paprika", amount: "1 tbsp" },
      { name: "Tomato purée", amount: "2 tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Chicken or beef stock", amount: "300ml" },
      { name: "Single cream", amount: "120ml" },
      { name: "Mozzarella, grated", amount: "60g" },
      { name: "Parsley and chilli flakes", amount: "to garnish" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Fry beef mince until browning. Add fajita seasoning, garlic powder and paprika.",
      "Cook pasta in salted boiling water in a separate pot.",
      "Add onion to beef and cook until soft. Add garlic, tomato purée and honey. Cook a few minutes.",
      "Add stock and cream. Cook until sauce thickens.",
      "Stir in drained pasta and mozzarella. Garnish with parsley and chilli flakes.",
    ],
    notes: "Goes well with a dollop of sour cream on top.",
    createdAt: Date.now() - 67000000,
  },
  {
    id: "creamy-red-pesto-chicken-1",
    title: "Creamy Red Pesto Chicken, Bacon & Potatoes",
    description: "Crispy potatoes and chicken with bacon in a creamy red pesto sauce, finished with melted cheese. About €12 for 3 portions.",
    tags: ["Chicken", "Dinner"],
    servings: 3,
    prepTime: "15 min",
    cookTime: "35 min",
    ingredients: [
      { name: "Potatoes, cubed", amount: "800g" },
      { name: "Chicken breast, diced", amount: "500g" },
      { name: "Bacon, diced", amount: "150g" },
      { name: "Onion, finely diced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "4" },
      { name: "Smoked paprika", amount: "1 tbsp" },
      { name: "Garlic granules", amount: "1½ tbsp" },
      { name: "Dried oregano", amount: "½ tbsp" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Red pesto", amount: "4 tbsp" },
      { name: "Chicken stock", amount: "300ml" },
      { name: "Single cream", amount: "120ml" },
      { name: "Cheddar and mozzarella mix, grated", amount: "120g" },
      { name: "Chilli flakes and parsley", amount: "to garnish" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Season potatoes with garlic granules, salt and pepper. Air fry at 190°C for 20 minutes until crispy.",
      "Season chicken and fry with bacon until browning.",
      "Add onion and cook until soft. Add garlic, tomato purée and red pesto. Stir well.",
      "Add stock and cream. Cook until sauce thickens.",
      "Add crispy potatoes and mix. Scatter cheese on top and grill until bubbling.",
      "Garnish with chilli flakes and parsley.",
    ],
    notes: "Use the full jar of pesto and a bit less stock — more pesto flavour is always better here.",
    createdAt: Date.now() - 66000000,
  },
  {
    id: "portobello-mushroom-mulitas-1",
    title: "Portobello Mushroom Mulitas",
    description: "Crispy fried tortilla sandwiches stuffed with charred portobello mushrooms and melted mozzarella, with chipotle mayo. About €13 for 2 portions.",
    tags: ["Vegetarian", "Dinner"],
    servings: 2,
    prepTime: "15 min",
    cookTime: "15 min",
    ingredients: [
      { name: "Portobello mushrooms, thickly sliced", amount: "4 large" },
      { name: "Small corn tortillas", amount: "8" },
      { name: "Firm mozzarella, grated", amount: "150g" },
      { name: "Chipotle paste", amount: "4 tsp" },
      { name: "Mayonnaise", amount: "4 tbsp" },
      { name: "Fresh coriander, finely chopped", amount: "small bunch" },
      { name: "Butter, softened", amount: "50g" },
      { name: "Dried oregano", amount: "1 tsp" },
      { name: "Smoked paprika", amount: "1 tsp" },
      { name: "Vegetable oil", amount: "for frying" },
      { name: "Lime", amount: "1" },
    ],
    method: [
      "Mix chipotle paste into mayonnaise. Mash coriander into softened butter. Set both aside.",
      "Heat pan until smoking hot. Toss mushrooms with oregano and paprika. Cook 1 minute per side until charred. Season with salt and lime juice.",
      "Spread 4 tortillas with chipotle mayo and mozzarella. Add mushrooms, a knob of coriander butter and more cheese. Top with remaining tortillas.",
      "Fry mulitas over medium heat for 1 minute, pressing down firmly. Flip confidently and cook until crisp and cheese is melted.",
      "Halve and serve with lime wedges and remaining chipotle mayo.",
    ],
    notes: "The flip is the hard part — press down firmly and commit. Corn tortillas give the best crunch.",
    createdAt: Date.now() - 65000000,
  },
  {
    id: "lemon-butter-prawn-linguini-1",
    title: "Lemon Butter Prawn Linguini",
    description: "Silky linguini in a glossy lemon butter sauce with garlic and parmesan. Fast, fresh and a bit special. About €14 for 4 portions.",
    tags: ["Fish", "Pasta", "Dinner", "Quick"],
    servings: 4,
    prepTime: "5 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Linguini", amount: "400g" },
      { name: "Raw prawns, peeled and deveined", amount: "500g" },
      { name: "Garlic cloves, finely chopped", amount: "4" },
      { name: "Butter", amount: "70g" },
      { name: "Olive oil", amount: "2 tbsp" },
      { name: "Lemon, zested and juiced", amount: "1" },
      { name: "Parmesan, grated", amount: "50g" },
      { name: "Chilli flakes", amount: "to taste" },
      { name: "Salt and black pepper", amount: "to taste" },
    ],
    method: [
      "Cook linguini in well-salted water. Reserve 1 cup pasta water before draining.",
      "Heat olive oil in a large pan over medium-high. Cook prawns 1–2 minutes per side until just pink. Remove to a plate.",
      "Reduce heat to medium. Add butter, garlic and chilli flakes. Cook 30–60 seconds until fragrant.",
      "Add a splash of pasta water and let it bubble to create a glossy emulsion.",
      "Add linguini and toss to coat, adding more pasta water if dry.",
      "Return prawns and add lemon zest, juice and parmesan. Toss until silky. Serve immediately.",
    ],
    notes: "Pull the prawns off the heat the moment they turn pink — they finish cooking in the sauce.",
    createdAt: Date.now() - 10800000,
  },
  {
    id: "creamy-chorizo-spinach-gnocchi-1",
    title: "Creamy Chorizo & Spinach Gnocchi",
    description: "Pan-fried gnocchi with crispy chorizo in a quick creamy tomato sauce. No boiling needed. About €10 for 4 portions.",
    tags: ["Dinner", "Quick"],
    servings: 4,
    prepTime: "5 min",
    cookTime: "15 min",
    ingredients: [
      { name: "Fresh gnocchi", amount: "500g" },
      { name: "Chorizo, diced", amount: "225g" },
      { name: "Onion, diced", amount: "1 small" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Tomato purée", amount: "1 tbsp" },
      { name: "Single cream", amount: "150ml" },
      { name: "Italian seasoning", amount: "1 tsp" },
      { name: "Fresh spinach", amount: "1 bag" },
      { name: "Parmesan, grated", amount: "to serve" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Pan-fry chorizo until crispy. Remove and set aside.",
      "Add onion and garlic to the same pan. Cook 3 minutes until soft.",
      "Add gnocchi straight into the pan — no boiling. Fry 3–4 minutes until lightly golden.",
      "Add tomato purée, cream, Italian seasoning, salt and pepper. Stir to coat.",
      "Stir in spinach until wilted. Add chorizo back in and mix through.",
      "Serve with parmesan.",
    ],
    notes: "Fresh gnocchi from the chilled section works best here. More chorizo is always the right call.",
    createdAt: Date.now() - 21600000,
  },
  {
    id: "cajun-chicken-chorizo-orzo-1",
    title: "Cajun Chicken & Chorizo Orzo Bake",
    description: "One-pan orzo cooked in spiced chicken stock with crispy chorizo, cream and spinach. About 30 minutes start to finish. About €12 for 4 portions.",
    tags: ["Chicken", "Dinner", "Quick"],
    servings: 4,
    prepTime: "5 min",
    cookTime: "25 min",
    ingredients: [
      { name: "Chicken breasts, diced", amount: "2" },
      { name: "Chorizo, sliced", amount: "150g" },
      { name: "Onion, diced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Orzo", amount: "300g" },
      { name: "Cajun seasoning", amount: "1 tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Chicken stock", amount: "600ml" },
      { name: "Single cream", amount: "150ml" },
      { name: "Fresh spinach", amount: "1 bag" },
      { name: "Cheddar, grated", amount: "to top" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Fry chorizo until crispy. Remove and set aside.",
      "In the same pan, fry chicken until lightly golden.",
      "Add onion and garlic, cook 2–3 minutes.",
      "Stir in Cajun seasoning and honey. Add orzo and chicken stock. Bring to a simmer.",
      "Cook 10–12 minutes, stirring regularly, until orzo is tender.",
      "Stir in cream, spinach and chorizo. Season to taste.",
      "Top with cheddar and let melt before serving.",
    ],
    notes: "Stir the orzo regularly — it likes to stick. Add a splash more stock if it looks dry before it's cooked.",
    createdAt: Date.now() - 43200000,
  },
  {
    id: "chicken-enchiladas-1",
    title: "Chicken Enchiladas",
    description: "Bold, saucy enchiladas with spiced chicken, peppers and onion baked in passata. About €12 for 4 portions.",
    tags: ["Chicken", "Dinner"],
    servings: 4,
    prepTime: "20 min",
    cookTime: "30 min",
    ingredients: [
      { name: "Chicken breasts or thighs", amount: "600g" },
      { name: "Flour tortillas, medium", amount: "8" },
      { name: "Mixed peppers, sliced", amount: "2" },
      { name: "Onion, sliced", amount: "1 large" },
      { name: "Garlic cloves, minced", amount: "3" },
      { name: "Passata", amount: "500ml" },
      { name: "Ground cumin", amount: "2 tsp" },
      { name: "Smoked paprika", amount: "1 tsp" },
      { name: "Chilli flakes", amount: "½ tsp" },
      { name: "Olive oil", amount: "2 tbsp" },
      { name: "Cheddar or mozzarella, grated", amount: "100g" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Preheat oven to 200°C. Season and cook chicken until cooked through. Rest then shred.",
      "In the same pan, fry onion, peppers and garlic for 8–10 minutes until soft.",
      "Add cumin, paprika and chilli. Stir 1 minute, then add 250ml passata. Simmer 5 minutes.",
      "Mix chicken through the pepper and sauce mixture.",
      "Spread a thin layer of passata on the base of an oven dish. Fill each tortilla with the chicken mix, roll tightly and place seam-down.",
      "Pour remaining passata over the top. Scatter cheese.",
      "Bake 20–25 minutes until bubbling and golden on top.",
    ],
    notes: "Cook a double batch of chicken — use the extra in pasta or wraps later in the week.",
    createdAt: Date.now() - 72000000,
  },
  {
    id: "creamy-chicken-pepper-pasta-1",
    title: "Creamy Chicken & Pepper Pasta",
    description: "A rich, comforting pasta using the same veg as enchilada night. Totally different feel — not like leftovers. About €10 for 4 portions.",
    tags: ["Chicken", "Pasta", "Dinner", "Quick"],
    servings: 4,
    prepTime: "10 min",
    cookTime: "20 min",
    ingredients: [
      { name: "Pasta (rigatoni or penne)", amount: "350g" },
      { name: "Cooked chicken, sliced or shredded", amount: "400g" },
      { name: "Mixed peppers, sliced", amount: "2" },
      { name: "Onion, sliced", amount: "1" },
      { name: "Garlic cloves, minced", amount: "2" },
      { name: "Double cream or crème fraîche", amount: "200ml" },
      { name: "Baby spinach", amount: "80g" },
      { name: "Parmesan, grated", amount: "40g" },
      { name: "Olive oil", amount: "1 tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    method: [
      "Cook pasta in well-salted water until al dente. Reserve a mug of pasta water before draining.",
      "Heat oil in a large pan. Fry onion, peppers and garlic for 8 minutes until soft.",
      "Add cooked chicken and stir through to heat.",
      "Pour in cream and a splash of pasta water. Simmer 2–3 minutes until slightly thickened.",
      "Toss in spinach until wilted. Add drained pasta and toss everything together.",
      "Serve with parmesan on top.",
    ],
    notes: "Crème fraîche gives a tangier, lighter result than double cream. Both work great.",
    createdAt: Date.now() - 58000000,
  },
  {
    id: "flatbread-chicken-wraps-1",
    title: "Flatbread Chicken Wraps",
    description: "Harissa-spiked chicken in warm flatbreads with a quick garlic yogurt sauce. Tastes like a takeaway. About €8 for 4 portions.",
    tags: ["Chicken", "Dinner", "Quick"],
    servings: 4,
    prepTime: "15 min",
    cookTime: "15 min",
    ingredients: [
      { name: "Cooked chicken, sliced", amount: "400g" },
      { name: "Flatbreads or naan", amount: "4" },
      { name: "Harissa paste or peri-peri sauce", amount: "2 tbsp" },
      { name: "Mixed peppers, sliced", amount: "1" },
      { name: "Onion, sliced", amount: "½" },
      { name: "Cucumber, thinly sliced", amount: "½" },
      { name: "Greek yogurt", amount: "150g" },
      { name: "Garlic clove, minced", amount: "1" },
      { name: "Lemon, juiced", amount: "½" },
      { name: "Salt", amount: "to taste" },
    ],
    method: [
      "Mix yogurt with garlic, lemon juice and a pinch of salt to make the garlic sauce.",
      "Toss chicken with harissa. Heat in a pan 3–4 minutes until hot and slightly charred.",
      "In the same pan, fry peppers and onion for 3–4 minutes.",
      "Warm flatbreads in a dry pan for 30 seconds each side.",
      "Spread garlic yogurt on each flatbread, top with chicken, peppers and cucumber. Wrap and serve.",
    ],
    notes: "The harissa completely changes the flavour from the enchiladas — it won't feel repetitive. A squeeze of extra lemon makes it pop.",
    createdAt: Date.now() - 44000000,
  },
];
